Add metadata-json-lint check

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -51,6 +51,13 @@ function checkyaml() {
     exit 1
  fi
 
+ path_to_metadata_json_lint=$(command -v metadata-json-lint)
+ if ! [ -x "$path_to_metadata_json_lint" ] ; then
+    echo "The metadata-json-lint binary wasn't found."
+    echo "Please run: 'gem install metadata-json-lint' and try again."
+    exit 1
+ fi
+
 echo "### Checking puppet syntax, for science! ###"
 # for file in `git diff --name-only --cached | grep -E '\.(pp|erb)'`
 for file in `git diff --name-only --cached | grep -E '\.(pp)'`
@@ -139,6 +146,23 @@ do
             syntax_is_bad=1
         else
             echo "OK: $file looks like a valid YAML file"
+        fi
+    fi
+done
+echo ""
+
+echo "### Checking if metadata.json syntax is valid ###"
+for file in `git diff --name-only --cached | grep 'metadata.json'`
+do
+    if [[ -f $file ]]
+    then
+        metadata-json-lint $file
+        if [[ $? -ne 0 ]]
+        then
+            echo "ERROR: metadata.json syntax validation failed"
+            syntax_is_bad=1
+        else
+            echo "OK: $file looks like a valid file"
         fi
     fi
 done
